# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# Data reduction workflow configuration template

name:
reference:
preprocess:
process:
postprocess:
new-input: # ADD|APPEND|REPLACE|SKIP
new-result: # ADD|APPEND|REPLACE|SKIP
save: # true/false
